import type { Profile, Match, Message } from "./types";

// Seed-based avatar generator using DiceBear API for consistent, unique avatars
function avatar(seed: string, style: "adventurer" | "avataaars" = "adventurer") {
  return `https://api.dicebear.com/9.x/${style}/svg?seed=${encodeURIComponent(seed)}&backgroundColor=b6e3f4,c0aede,d1d4f9,ffd5dc,ffdfbf`;
}

export const MOCK_PROFILES: Profile[] = [
  {
    id: "p1",
    name: "Maya Chen",
    age: 20,
    college: "SCS",
    major: "Computer Science",
    gradYear: 2027,
    bio: "Building the future one commit at a time. Love late-night coding sessions at Gates and early morning runs around Schenley Park.",
    interests: ["Coffee", "Robotics", "Hiking", "Photography"],
    photos: [avatar("maya-chen-1"), avatar("maya-chen-2", "avataaars")],
    matchMode: ["dating", "study"],
    lookingFor: "Someone who can explain monads AND hold a conversation",
  },
  {
    id: "p2",
    name: "Jordan Williams",
    age: 21,
    college: "CFA",
    major: "Architecture",
    gradYear: 2026,
    bio: "If I'm not in studio, I'm probably at Conflict Kitchen. I design spaces that make people feel something.",
    interests: ["Art", "Photography", "Coffee", "Travel"],
    photos: [avatar("jordan-w-1"), avatar("jordan-w-2", "avataaars")],
    matchMode: ["dating"],
    lookingFor: "A creative soul who appreciates good design",
  },
  {
    id: "p3",
    name: "Priya Patel",
    age: 19,
    college: "Tepper",
    major: "Business Administration",
    gradYear: 2028,
    bio: "Future CEO in the making. When I'm not crunching numbers, you'll find me at the gym or trying new restaurants in Squirrel Hill.",
    interests: ["Fitness", "Cooking", "Startups", "Dance"],
    photos: [avatar("priya-p-1"), avatar("priya-p-2", "avataaars")],
    matchMode: ["dating", "study"],
    lookingFor: "An ambitious go-getter who knows how to have fun",
  },
  {
    id: "p4",
    name: "Alex Kim",
    age: 20,
    college: "SCS",
    major: "Artificial Intelligence",
    gradYear: 2027,
    bio: "Training neural nets by day, training for marathons by night. Ask me about my thesis on reinforcement learning.",
    interests: ["Robotics", "Fitness", "Gaming", "Coffee"],
    photos: [avatar("alex-kim-1"), avatar("alex-kim-2", "avataaars")],
    matchMode: ["study", "dating"],
    lookingFor: "Someone to debate AI ethics with over ramen",
  },
  {
    id: "p5",
    name: "Sophia Rodriguez",
    age: 21,
    college: "Dietrich",
    major: "Psychology",
    gradYear: 2026,
    bio: "I can analyze your dreams but not my own sleep schedule. Resident Hunt Library bookworm and amateur photographer.",
    interests: ["Reading", "Photography", "Music", "Coffee"],
    photos: [avatar("sophia-r-1"), avatar("sophia-r-2", "avataaars")],
    matchMode: ["dating"],
    lookingFor: "Someone who's emotionally intelligent and intellectually curious",
  },
  {
    id: "p6",
    name: "Marcus Thompson",
    age: 22,
    college: "CIT",
    major: "Mechanical Engineering",
    gradYear: 2025,
    bio: "Building robots at Roboclub and bridges in my spare time. Senior year means I actually sleep sometimes. Buggy champion '24.",
    interests: ["Robotics", "Fitness", "Board Games", "Hiking"],
    photos: [avatar("marcus-t-1"), avatar("marcus-t-2", "avataaars")],
    matchMode: ["dating", "study"],
    lookingFor: "Someone who appreciates both brains and brawn",
  },
  {
    id: "p7",
    name: "Lily Zhang",
    age: 20,
    college: "MCS",
    major: "Physics",
    gradYear: 2027,
    bio: "Quantum mechanics is easier than dating. Change my mind. You'll find me stargazing on the Cut or doing problem sets at Entropy+.",
    interests: ["Reading", "Hiking", "Music", "Board Games"],
    photos: [avatar("lily-z-1"), avatar("lily-z-2", "avataaars")],
    matchMode: ["dating", "study"],
    lookingFor: "Someone who thinks the universe is as fascinating as I do",
  },
  {
    id: "p8",
    name: "Daniel Okafor",
    age: 21,
    college: "SCS",
    major: "Human-Computer Interaction",
    gradYear: 2026,
    bio: "Making tech more human, one interface at a time. DJ on WRCT and avid Scotty Dog enthusiast.",
    interests: ["Music", "Art", "Dance", "Gaming"],
    photos: [avatar("daniel-o-1"), avatar("daniel-o-2", "avataaars")],
    matchMode: ["dating"],
    lookingFor: "Someone who vibes with good music and great conversation",
  },
  {
    id: "p9",
    name: "Emma Sullivan",
    age: 19,
    college: "CFA",
    major: "Drama",
    gradYear: 2028,
    bio: "Life's a stage and I'm not just acting. Catch me at the Playground or singing in the Originals. I give great monologues on first dates.",
    interests: ["Music", "Dance", "Film", "Coffee"],
    photos: [avatar("emma-s-1"), avatar("emma-s-2", "avataaars")],
    matchMode: ["dating"],
    lookingFor: "Someone who's not afraid to be dramatic (in a good way)",
  },
  {
    id: "p10",
    name: "Ryan Nakamura",
    age: 20,
    college: "SDS",
    major: "Design",
    gradYear: 2027,
    bio: "Pixel-perfect in Figma, perfectly imperfect IRL. I photograph campus at golden hour and make a mean pour-over.",
    interests: ["Photography", "Art", "Coffee", "Travel"],
    photos: [avatar("ryan-n-1"), avatar("ryan-n-2", "avataaars")],
    matchMode: ["dating", "study"],
    lookingFor: "Someone aesthetically pleasing inside and out",
  },
  {
    id: "p11",
    name: "Aisha Mohammed",
    age: 21,
    college: "SCS",
    major: "Software Engineering",
    gradYear: 2026,
    bio: "Open source contributor and open book. Love organizing hackathons and hiking in Frick Park. My code compiles on the first try (sometimes).",
    interests: ["Hiking", "Startups", "Coffee", "Board Games"],
    photos: [avatar("aisha-m-1"), avatar("aisha-m-2", "avataaars")],
    matchMode: ["dating", "study"],
    lookingFor: "A fellow builder who also knows when to touch grass",
  },
  {
    id: "p12",
    name: "Chris Anderson",
    age: 22,
    college: "Tepper",
    major: "Finance",
    gradYear: 2025,
    bio: "Bull market or bear market, I'm always bullish on good company. Captain of the club tennis team and amateur chef.",
    interests: ["Fitness", "Cooking", "Travel", "Startups"],
    photos: [avatar("chris-a-1"), avatar("chris-a-2", "avataaars")],
    matchMode: ["dating"],
    lookingFor: "Someone ambitious with a great sense of humor",
  },
];

export const INITIAL_MATCHES: Match[] = [
  {
    id: "m1",
    profileId: "p5",
    matchedAt: Date.now() - 86400000 * 2,
    mode: "dating",
    lastMessage: "Have you been to the new exhibit at the Mattress Factory?",
    lastMessageAt: Date.now() - 3600000,
    unread: 1,
  },
  {
    id: "m2",
    profileId: "p6",
    matchedAt: Date.now() - 86400000,
    mode: "study",
    lastMessage: "Want to study for the thermo exam at Gates?",
    lastMessageAt: Date.now() - 7200000,
    unread: 0,
  },
];

export const INITIAL_MESSAGES: Message[] = [
  {
    id: "msg1",
    matchId: "m1",
    senderId: "p5",
    text: "Hey! I love your photography 📸",
    timestamp: Date.now() - 86400000 * 2,
  },
  {
    id: "msg2",
    matchId: "m1",
    senderId: "me",
    text: "Thanks! I saw your shots of Hunt Library - amazing light",
    timestamp: Date.now() - 86400000 * 2 + 3600000,
  },
  {
    id: "msg3",
    matchId: "m1",
    senderId: "p5",
    text: "Have you been to the new exhibit at the Mattress Factory?",
    timestamp: Date.now() - 3600000,
  },
  {
    id: "msg4",
    matchId: "m2",
    senderId: "p6",
    text: "Hey! We matched for study mode 🤓",
    timestamp: Date.now() - 86400000,
  },
  {
    id: "msg5",
    matchId: "m2",
    senderId: "me",
    text: "Awesome! What classes are you taking?",
    timestamp: Date.now() - 86400000 + 1800000,
  },
  {
    id: "msg6",
    matchId: "m2",
    senderId: "p6",
    text: "Want to study for the thermo exam at Gates?",
    timestamp: Date.now() - 7200000,
  },
];

export const MY_PROFILE: Profile = {
  id: "me",
  name: "You",
  age: 20,
  college: "SCS",
  major: "Computer Science",
  gradYear: 2027,
  bio: "Just a CMU student looking for connections",
  interests: ["Coffee", "Hiking", "Gaming", "Music"],
  photos: [avatar("my-profile")],
  matchMode: ["dating", "study"],
  lookingFor: "Someone special",
};
